name: 'Build app then push to pages'

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'build') }}
    environment: web-deployment
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: echo ${{env}}
        shell: bash
      - run: flutter build web --release --base-href "/scf/" --dart-define=DATABASE_URL=${{ secrets.DATABASE_URL }}
        shell: bash
        working-directory: .
      - run: git config user.name github-actions
        shell: bash
        working-directory: .
      - run: git config user.email github-actions@github.com
        shell: bash
        working-directory: .
      - run: git --work-tree build/web add --all
        shell: bash
        working-directory: .
      - run: git commit -m "Automatic deployment by github-actions"
        shell: bash
        working-directory: .
      - run: git push origin HEAD:pages --force
        shell: bash
        working-directory: .
